PLIP 10902: New collections
===========================

PLIP ticket: http://dev.plone.org/plone/ticket/10902

Review by Ross Patterson (me@rpatterson.net, zenwryly on irc)

The PLIP was reviewed on Ubuntu 10.10 (Maverick) using python 2.6.6
and Google Chrome 9.0.


Review steps
------------

- Ran the plips/plip10902-new-collections.cfg buildout.

- Ran tests for plone.app.contentlisting, plone.app.collection,
  plone.app.querystring, and archetypes.querywidget.

- Ran bin/alltests.

- Created a new Plone site with the plone.app.collection add-on
  included.

- Added several collections using the new UI.

- Examined code.


Notes and observations
----------------------

- The README.txt and description in setup.py are empty for
  plone.app.collection, plone.app.querystring, and
  archetypes.querywidget.  These should have some minimal content at
  the very least, preferably they should explain the package for those
  who might want to re-use it.

- plone.app.contentlisting/README.txt doesn't provide nearly enough of
  a high level description, especially for a package intended for
  re-use such as this.

- archetypes.querywidget/setup.py only requires plone.app.querystring
  but archetypes/querywidget/configure.zcml includes
  plone.app.vocabularies and plone.app.contentlisting as well.  If
  archetypes.querywidget actually does depend on the ZCML of those two
  eggs, then they should be added as dependencies in setup.py,
  otherwise those ZCML includes should be removed.

- Cleaned up a bunch of testing dependency issues.

- Added alltests test-groups eggs.

- plone.app.querystring/setup.py depends on plone.directives.form, but
  I don't see anything that uses it.

- The GenericSetup profiles need better titles and descriptions so
  that users can know what they're looking at when installing add-ons.

- The results preview is damn cool!  Everything works as it should.

- I love the per-criteria counts, *very* useful.

- The results preview could be a little clearer by saying "3 of 22
  results" instead of just "22 results" and showing only 3.

- I think the "Remove line" link in the criteria editing should have
  something to call it out, probably whatever icon we use in Plone for
  deleting/removing, such as a red X.

- The criteria value dropdowns don't seem to go away when you click
  elsewhere on the page.

- The criteria value dropdowns are styled differently than other
  dropdowns.

- The date criteria value isn't using a calendar widget nor is any
  description given of how to enter a textual date.  I think this
  might be important enough to be a must-have.

- Since this is meant to be the new canonical Collection
  implementation, shouldn't the Plone default News, Events, and Past
  Events collections use this new implantation when creating new
  sites?

- Fixed some logging issues, was getting *way* too many "... INFO
  plone.app.querystring Generated query: ..." log messages.  Switched
  from INFO to DEBUG.

- Plone handled the following error several times.  This needs to be
  addressed.

    User Name
    admin (admin)
    Request URL
    http://localhost:8080/Plone/@@querybuilder_html_results
    Exception Type
    BadRequest
    Exception Value
    <h2>Site Error</h2> <p>An error was encountered while publishing this resource. </p> <p><strong>Invalid request</strong></p> The parameter, <em>query</em>, was omitted from the request.<p>Make sure to specify all required parameters, and try the request again.</p> <hr noshade="noshade"/> <p>Troubleshooting Suggestions</p> <ul> <li>The URL may be incorrect.</li> <li>The parameters passed to this resource may be incorrect.</li> <li>A resource that this resource relies on may be encountering an error.</li> </ul> <p>For more detailed information about the error, please refer to the error log. </p> <p>If the error persists please contact the site maintainer. Thank you for your patience. </p>
    Traceback (innermost last):
    
    Module ZPublisher.Publish, line 126, in publish
    Module ZPublisher.mapply, line 72, in mapply
    Module ZPublisher.Publish, line 51, in missing_name
    Module ZPublisher.HTTPResponse, line 741, in badRequestError
    BadRequest: <h2>Site Error</h2> <p>An error was encountered while publishing this resource. </p> <p><strong>Invalid request</strong></p> The parameter, <em>query</em>, was omitted from the request.<p>Make sure to specify all required parameters, and try the request again.</p> <hr noshade="noshade"/> <p>Troubleshooting Suggestions</p> <ul> <li>The URL may be incorrect.</li> <li>The parameters passed to this resource may be incorrect.</li> <li>A resource that this resource relies on may be encountering an error.</li> </ul> <p>For more detailed information about the error, please refer to the error log. </p> <p>If the error persists please contact the site maintainer. Thank you for your patience. </p>
    
    Display traceback as text
    
    REQUEST
    form
    cookies
    dtpref_rows	'20'
    zmi_top_frame	''
    dtpref_cols	'100%'
    tree-s	'eJzT0MgpMOQKVneEA1dbda4CI67EkgJjLj0AeGcHew'
    zmi_use_css	'1'
    lazy items
    SESSION	<bound method SessionDataManager.getSessionData of <SessionDataManager at /session_data_manager>>
    other
    AUTHENTICATION_PATH	''
    TraversalRequestNameStack	[]
    LANGUAGE	'en'
    AUTHENTICATED_USER	<PropertiedUser 'admin'>
    URL	'http://localhost:8080/Plone/@@querybuilder_html_results'
    SERVER_URL	'http://localhost:8080'
    LANGUAGE_TOOL	<Products.PloneLanguageTool.LanguageTool.LanguageBinding instance at 0xd8a51cc>
    PUBLISHED	<Products.Five.metaclass.QueryBuilder object at 0xd8a5b0c>
    method	'GET'
    ACTUAL_URL	'http://localhost:8080/Plone/@@querybuilder_html_results'
    URL0	http://localhost:8080/Plone/@@querybuilder_html_results
    URL1	http://localhost:8080/Plone
    URL2	http://localhost:8080
    BASE0	http://localhost:8080
    BASE1	http://localhost:8080
    BASE2	http://localhost:8080/Plone
    BASE3	http://localhost:8080/Plone/@@querybuilder_html_results
    environ
    CONNECTION_TYPE	'keep-alive'
    HTTP_USER_AGENT	'Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.13 (KHTML, like Gecko) Chrome/9.0.597.0 Safari/534.13'
    HTTP_COOKIE	'dtpref_rows="20"; zmi_top_frame=""; dtpref_cols="100%"; zmi_use_css="1"; tree-s="eJzT0MgpMOQKVneEA1dbda4CI67EkgJjLj0AeGcHew"'
    SERVER_NAME	'localhost6.localdomain6'
    GATEWAY_INTERFACE	'CGI/1.1'
    HTTP_ACCEPT	'application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5'
    SERVER_SOFTWARE	'Zope/(2.13.1dev, python 2.6.6, linux2) ZServer/1.1'
    REMOTE_ADDR	'127.0.0.1'
    HTTP_ACCEPT_LANGUAGE	'en-US,en;q=0.8'
    SCRIPT_NAME	''
    REQUEST_METHOD	'GET'
    HTTP_HOST	'localhost:8080'
    PATH_INFO	'/Plone/@@querybuilder_html_results'
    SERVER_PORT	'8080'
    SERVER_PROTOCOL	'HTTP/1.1'
    QUERY_STRING	''
    HTTP_ACCEPT_CHARSET	'ISO-8859-1,utf-8;q=0.7,*;q=0.3'
    channel.creation_time	1291695482
    HTTP_ACCEPT_ENCODING	'gzip,deflate,sdch'
    PATH_TRANSLATED	'/Plone/@@querybuilder_html_results'

- No obviously related errors from bin/alltests that weren't exposed
  with bin/test below.

- ran "bin/test -s plone.app.contentlisting -s plone.app.collection -s
  plone.app.querystring -s archetypes.querywidget" and got the
  following.  This should be addressed:

      Set up plone.app.testing.layers.PloneFixture Traceback (most recent call last):
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 367, in run_layer
        setup_layer(options, layer, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 632, in setup_layer
        layer.setUp()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 110, in setUp
        self.setUpZCML()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 222, in setUpZCML
        loadAll('configure.zcml')
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 217, in loadAll
        xmlconfig.file(filename, package, context=context)
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 653, in file
        context.execute_actions()
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 606, in execute_actions
        callable(*args, **kw)
      File "/usr/local/lib/python/site-packages/Products.GenericSetup-1.6.1-py2.6.egg/Products/GenericSetup/registry.py", line 707, in registerProfile
        raise KeyError, 'Duplicate profile ID: %s' % profile_id
    ConfigurationExecutionError: <type 'exceptions.KeyError'>: u'Duplicate profile ID: Products.CMFUid:default'
      in:
      File "/usr/local/lib/python/site-packages/Products.CMFUid-2.2.1-py2.6.egg/Products/CMFUid/configure.zcml", line 10.2-16.8
        <genericsetup:registerProfile
            name="default"
            title="CMFUid"
            description="Adds UID support."
            provides="Products.GenericSetup.interfaces.EXTENSION"
            for="Products.CMFCore.interfaces.ISiteRoot"
            />
    
    
    Running plone.app.collection.tests.base.PACollection:Functional tests:
      Set up plone.app.testing.layers.PloneFixture Traceback (most recent call last):
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 367, in run_layer
        setup_layer(options, layer, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 632, in setup_layer
        layer.setUp()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 110, in setUp
        self.setUpZCML()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 222, in setUpZCML
        loadAll('configure.zcml')
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 217, in loadAll
        xmlconfig.file(filename, package, context=context)
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 653, in file
        context.execute_actions()
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 606, in execute_actions
        callable(*args, **kw)
      File "/usr/local/lib/python/site-packages/Products.GenericSetup-1.6.1-py2.6.egg/Products/GenericSetup/registry.py", line 707, in registerProfile
        raise KeyError, 'Duplicate profile ID: %s' % profile_id
    ConfigurationExecutionError: <type 'exceptions.KeyError'>: u'Duplicate profile ID: Products.CMFDefault:default'
      in:
      File "/usr/local/lib/python/site-packages/Products.CMFDefault-2.2.2-py2.6.egg/Products/CMFDefault/profiles.zcml", line 6.2-11.8
        <genericsetup:registerProfile
            name="default"
            title="CMFDefault Site"
            description="Profile for a default CMFSite."
            for="Products.CMFCore.interfaces.ISiteRoot"
            />
    
    
    Running plone.app.contentlisting.tests.base.ContentListing:Functional tests:
      Set up plone.app.testing.layers.PloneFixture Traceback (most recent call last):
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 367, in run_layer
        setup_layer(options, layer, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 627, in setup_layer
        setup_layer(options, base, setup_layers)
      File "/usr/local/lib/python/site-packages/zope.testing-3.9.4-py2.6.egg/zope/testing/testrunner/runner.py", line 632, in setup_layer
        layer.setUp()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 110, in setUp
        self.setUpZCML()
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 222, in setUpZCML
        loadAll('configure.zcml')
      File "/home/xen/src/plone-coredev.svn/src/plone.app.testing/plone/app/testing/layers.py", line 217, in loadAll
        xmlconfig.file(filename, package, context=context)
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 653, in file
        context.execute_actions()
      File "/usr/local/lib/python/site-packages/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 606, in execute_actions
        callable(*args, **kw)
      File "/usr/local/lib/python/site-packages/Products.GenericSetup-1.6.1-py2.6.egg/Products/GenericSetup/registry.py", line 707, in registerProfile
        raise KeyError, 'Duplicate profile ID: %s' % profile_id
    ConfigurationExecutionError: <type 'exceptions.KeyError'>: u'Duplicate profile ID: Products.PlonePAS:PlonePAS'
      in:
      File "/home/xen/src/plone-coredev.svn/src/Products.PlonePAS/Products/PlonePAS/profiles.zcml", line 6.2-12.8
        <genericsetup:registerProfile
            name="PlonePAS"
            title="PlonePAS"
            directory="profiles/default"
            description="Extension profile for default PlonePAS setup."
            provides="Products.GenericSetup.interfaces.EXTENSION"
            />

- It seems like the tabular_view has been factored out of the
  standard_view.  They were combined in atct_topic_view and I think
  it's great to factor them out this way.  I see that the "Display as
  Table" checkbox field has also been removed from the collection edit
  form, also good. But this does leave some confusion in play.  From
  the edit form it's not clear what the "Table Columns" field does
  especially since it's help text still refers to the "Display as
  Table" field.  Do we think it's sufficiently clear to just change
  the "Table Columns" help text to refer to selecting the right layout
  from the display menu back on the view screen?

- plone.app.collection, plone.app.querystring and
  archetypes.querywidget are in dire need of comments, docstrings and
  more complete interfaces for developer/maintenance documentation
  purposes.  It's far to difficult to approach and understand how
  things fit together as-is.

- Why is a new/separate collection portlet implementation provided in
  plone.app.collection?  Isn't the one in plone.portlet.collection
  already compatible?

- The javascriptDisabled validator seems distasteful to me, but I
  might not be understanding it.  Why is this necessary and is there
  really no better way?

- I love how small plone.app.collection is.

- It sure looks like the archetypes.querywidget.field.QueryField set
  and __init__ methods are entirely unnecessary.

- I don't see any unit tests for the JS.

- I note that the query builder JS lives in archetypes.querywidget.
  It seems like it would be best to have it factored out into a non-AT
  dependent place.  Would plone.app.querystring be the right place for
  that?

- The test coverage for archetypes.querywidget and
  plone.app.collection looks poor.

Conclusion
----------

The implementation is slick and really nice to use.  It's a vast
improvement over what we have currently.  I'd love to see it included
in 4.1.

Having said that I don't think I'm comfortable merging it as-is, but
the changes required seem to be pretty doable.  If more complete
docstrings, comments, and interfaces are added, the test failures are
addressed, and the BadRequest errors are addressed, I'm a strong +1
for merging.
